In [1]:
print("Hello world")

Hello world

In [2]:
import pandas as pd
from sklearn.datasets import fetch_openml

In [23]:
titanic = fetch_openml(name="titanic", version=1, as_frame=True)
data = pd.DataFrame(titanic.data)
data.head()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_arff_parser.py:200: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  frame = pd.concat(dfs, ignore_index=True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"

In [24]:
# Q1
data.isnull().sum()

# Filling NA values
data["age"].fillna(data["age"].mean(), inplace=True)
data["cabin"].fillna("UNKNOWN", inplace=True)

# Dropping some of the NA values
data.dropna(subset=["embarked"], inplace=True)

In [26]:
#Q2 Duplicate check
print(data.duplicated().sum())
data.drop_duplicates(inplace=True)

0

In [27]:
# Q3 Finding inconsistencies 
data.sex.unique()

['female', 'male']
Categories (2, object): ['female', 'male']

In [28]:
# Q4 Finding outliers 

def outlierCheck(df, colName):
    q1  = df[colName].quantile(0.25)
    q3 = df[colName].quantile(0.75)

    IQR = q3 - q1

    # Outliers filtering
    outliers = df.loc[(df[colName] < (q1 - 1.5*IQR)) | (df[colName] > (q3 + 1.5*IQR))]

    return outliers

In [42]:
outliers = outlierCheck(data, colName="age")
outliers.head(n=10)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,family_size
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,2,11,NaN,"Montreal, PQ / Chesterville, ON",4.0
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,2,None,NaN,"Montreal, PQ / Chesterville, ON",4.0
6,1.0,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1.0,0.0,13502,77.9583,D7,2,10,NaN,"Hudson, NY",2.0
9,1.0,"Artagaveytia, Mr. Ramon",male,71.0000,0.0,0.0,PC 17609,49.5042,UNKNOWN,0,None,22.0,"Montevideo, Uruguay",1.0
14,1.0,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0.0,0.0,27042,30.0000,A23,2,B,NaN,"Hessle, Yorks",1.0
33,1.0,"Bonnell, Miss. Elizabeth",female,58.0000,0.0,0.0,113783,26.5500,C103,2,8,NaN,"Birkdale, England Cleveland, Ohio",1.0
42,1.0,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0000,2.0,0.0,11769,51.4792,C101,2,D,NaN,"Belmont, MA",3.0
43,1.0,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0000,0.0,0.0,11813,76.2917,D15,0,8,NaN,"Philadelphia, PA",1.0
50,1.0,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0000,0.0,1.0,PC 17755,512.3292,B51 B53 B55,0,3,NaN,"Germantown, Philadelphia, PA",2.0
61,1.0,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0000,1.0,0.0,19877,78.8500,C46,2,6,NaN,"Little Onn Hall, Staffs",2.0

In [ ]:
# Q5 Creating a new col 
data["family_size"] = data["sibsp"] + data["parch"]  + 1
data.head()

In [ ]:
# Q6 Encoding - Label Encoder
from sklearn.preprocessing import LabelEncoder
data.embarked.unique()

label_encoder = LabelEncoder()

data["embarked"] = label_encoder.fit_transform(data["embarked"])

data.tail()

In [41]:
# Q8 
data.name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1307, dtype: object

In [ ]:
# Q9 Creating bins